apiVersion: apps/v1
kind: Deployment
metadata:
  name: technical-test
  labels:
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: php
      tier: backend
  template:
    metadata:
      labels:
        app: php
        tier: backend
    spec:
      volumes:
      - name: dir
        hostPath:
          path: /code            
      containers:
      - name: technical-test
        image: charlemagnepa/technical-test
        volumeMounts:
        - name: dir
          mountPath: /code
      imagePullSecrets:
      - name: regcred
      initContainers:
      - name: install
        image: busybox
        volumeMounts:
        - name: dir
          mountPath: /code
        command:
        - cp
        - "-r"
        - "/var/www/."
        - "/code/app"