kind: Service
apiVersion: v1
metadata:
  name: php
  labels:
    tier: backend
    app: php
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32380
  selector:
    tier: backend
    app: php
  type: LoadBalancer